import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const seedOptions = async () => {
  try {
    const existingOptions = await prisma.option.findMany({
      where: {
        OR: [
          { title: "Benar" },
          { title: "Salah" },
          { title: "Ya" },
          { title: "Tidak" },
          { title: "Tidak Pernah" },
          { title: "Jarang" },
          { title: "Sering" },
          { title: "Selalu" },
        ],
      },
    });

    if (existingOptions.length > 0) {
      console.log("Options already exist");
      return;
    }

    await prisma.option.createMany({
      data: [
        { question_id: 1, title: "Benar", score: 1 },
        { question_id: 1, title: "Salah", score: 0 },
        { question_id: 2, title: "Benar", score: 1 },
        { question_id: 2, title: "Salah", score: 0 },
        { question_id: 3, title: "Benar", score: 1 },
        { question_id: 3, title: "Salah", score: 0 },
        { question_id: 4, title: "Benar", score: 1 },
        { question_id: 4, title: "Salah", score: 0 },
        { question_id: 5, title: "Benar", score: 1 },
        { question_id: 5, title: "Salah", score: 0 },
        { question_id: 6, title: "Benar", score: 1 },
        { question_id: 6, title: "Salah", score: 0 },
        { question_id: 7, title: "Benar", score: 1 },
        { question_id: 7, title: "Salah", score: 0 },
        { question_id: 8, title: "Benar", score: 1 },
        { question_id: 8, title: "Salah", score: 0 },
        { question_id: 9, title: "Benar", score: 1 },
        { question_id: 9, title: "Salah", score: 0 },
        { question_id: 10, title: "Benar", score: 1 },
        { question_id: 10, title: "Salah", score: 0 },
        { question_id: 11, title: "Benar", score: 1 },
        { question_id: 11, title: "Salah", score: 0 },
        { question_id: 12, title: "Benar", score: 1 },
        { question_id: 12, title: "Salah", score: 0 },
        { question_id: 13, title: "Benar", score: 1 },
        { question_id: 13, title: "Salah", score: 0 },
        { question_id: 14, title: "Benar", score: 1 },
        { question_id: 14, title: "Salah", score: 0 },
        { question_id: 15, title: "Benar", score: 1 },
        { question_id: 15, title: "Salah", score: 0 },
        { question_id: 16, title: "Ya", score: 1 },
        { question_id: 16, title: "Tidak", score: 0 },
        { question_id: 17, title: "Ya", score: 1 },
        { question_id: 17, title: "Tidak", score: 0 },
        { question_id: 18, title: "Ya", score: 1 },
        { question_id: 18, title: "Tidak", score: 0 },
        { question_id: 19, title: "Ya", score: 1 },
        { question_id: 19, title: "Tidak", score: 0 },
        { question_id: 20, title: "Ya", score: 1 },
        { question_id: 20, title: "Tidak", score: 0 },
        { question_id: 21, title: "Ya", score: 1 },
        { question_id: 21, title: "Tidak", score: 0 },
        { question_id: 22, title: "Ya", score: 1 },
        { question_id: 22, title: "Tidak", score: 0 },
        { question_id: 23, title: "Ya", score: 1 },
        { question_id: 23, title: "Tidak", score: 0 },
        { question_id: 24, title: "Ya", score: 1 },
        { question_id: 24, title: "Tidak", score: 0 },
        { question_id: 25, title: "Ya", score: 1 },
        { question_id: 25, title: "Tidak", score: 0 },
        { question_id: 26, title: "Ya", score: 1 },
        { question_id: 26, title: "Tidak", score: 0 },
        { question_id: 27, title: "Ya", score: 1 },
        { question_id: 27, title: "Tidak", score: 0 },
        { question_id: 28, title: "Ya", score: 1 },
        { question_id: 28, title: "Tidak", score: 0 },
        { question_id: 29, title: "Ya", score: 1 },
        { question_id: 29, title: "Tidak", score: 0 },
        { question_id: 30, title: "Tidak Pernah", score: 1 },
        { question_id: 30, title: "Jarang", score: 2 },
        { question_id: 30, title: "Sering", score: 3 },
        { question_id: 30, title: "Selalu", score: 4 },
        { question_id: 31, title: "Tidak Pernah", score: 1 },
        { question_id: 31, title: "Jarang", score: 2 },
        { question_id: 31, title: "Sering", score: 3 },
        { question_id: 31, title: "Selalu", score: 4 },
        { question_id: 32, title: "Tidak Pernah", score: 1 },
        { question_id: 32, title: "Jarang", score: 2 },
        { question_id: 32, title: "Sering", score: 3 },
        { question_id: 32, title: "Selalu", score: 4 },
        { question_id: 33, title: "Tidak Pernah", score: 1 },
        { question_id: 33, title: "Jarang", score: 2 },
        { question_id: 33, title: "Sering", score: 3 },
        { question_id: 33, title: "Selalu", score: 4 },
        { question_id: 34, title: "Tidak Pernah", score: 1 },
        { question_id: 34, title: "Jarang", score: 2 },
        { question_id: 34, title: "Sering", score: 3 },
        { question_id: 34, title: "Selalu", score: 4 },
        { question_id: 35, title: "Tidak Pernah", score: 1 },
        { question_id: 35, title: "Jarang", score: 2 },
        { question_id: 35, title: "Sering", score: 3 },
        { question_id: 35, title: "Selalu", score: 4 },
        { question_id: 36, title: "Tidak Pernah", score: 1 },
        { question_id: 36, title: "Jarang", score: 2 },
        { question_id: 36, title: "Sering", score: 3 },
        { question_id: 36, title: "Selalu", score: 4 },
        { question_id: 37, title: "Tidak Pernah", score: 1 },
        { question_id: 37, title: "Jarang", score: 2 },
        { question_id: 37, title: "Sering", score: 3 },
        { question_id: 37, title: "Selalu", score: 4 },
        { question_id: 38, title: "Tidak Pernah", score: 1 },
        { question_id: 38, title: "Jarang", score: 2 },
        { question_id: 38, title: "Sering", score: 3 },
        { question_id: 38, title: "Selalu", score: 4 },
        { question_id: 39, title: "Tidak Pernah", score: 1 },
        { question_id: 39, title: "Jarang", score: 2 },
        { question_id: 39, title: "Sering", score: 3 },
        { question_id: 39, title: "Selalu", score: 4 },
        { question_id: 40, title: "Tidak Pernah", score: 1 },
        { question_id: 40, title: "Jarang", score: 2 },
        { question_id: 40, title: "Sering", score: 3 },
        { question_id: 40, title: "Selalu", score: 4 },
        { question_id: 41, title: "Tidak Pernah", score: 1 },
        { question_id: 41, title: "Jarang", score: 2 },
        { question_id: 41, title: "Sering", score: 3 },
        { question_id: 41, title: "Selalu", score: 4 },
        { question_id: 42, title: "Tidak Pernah", score: 1 },
        { question_id: 42, title: "Jarang", score: 2 },
        { question_id: 42, title: "Sering", score: 3 },
        { question_id: 42, title: "Selalu", score: 4 },
        { question_id: 43, title: "Tidak Pernah", score: 1 },
        { question_id: 43, title: "Jarang", score: 2 },
        { question_id: 43, title: "Sering", score: 3 },
        { question_id: 43, title: "Selalu", score: 4 },
        { question_id: 44, title: "Tidak Pernah", score: 1 },
        { question_id: 44, title: "Jarang", score: 2 },
        { question_id: 44, title: "Sering", score: 3 },
        { question_id: 44, title: "Selalu", score: 4 },
        { question_id: 45, title: "Tidak Pernah", score: 1 },
        { question_id: 45, title: "Jarang", score: 2 },
        { question_id: 45, title: "Sering", score: 3 },
        { question_id: 45, title: "Selalu", score: 4 },
        { question_id: 46, title: "Tidak Pernah", score: 1 },
        { question_id: 46, title: "Jarang", score: 2 },
        { question_id: 46, title: "Sering", score: 3 },
        { question_id: 46, title: "Selalu", score: 4 },
        { question_id: 47, title: "Tidak Pernah", score: 1 },
        { question_id: 47, title: "Jarang", score: 2 },
        { question_id: 47, title: "Sering", score: 3 },
        { question_id: 47, title: "Selalu", score: 4 },
        { question_id: 48, title: "Tidak Pernah", score: 1 },
        { question_id: 48, title: "Jarang", score: 2 },
        { question_id: 48, title: "Sering", score: 3 },
        { question_id: 48, title: "Selalu", score: 4 },
        { question_id: 49, title: "Tidak Pernah", score: 1 },
        { question_id: 49, title: "Jarang", score: 2 },
        { question_id: 49, title: "Sering", score: 3 },
        { question_id: 49, title: "Selalu", score: 4 },
        { question_id: 50, title: "Tidak Pernah", score: 1 },
        { question_id: 50, title: "Jarang", score: 2 },
        { question_id: 50, title: "Sering", score: 3 },
        { question_id: 50, title: "Selalu", score: 4 },
        { question_id: 51, title: "Tidak Pernah", score: 1 },
        { question_id: 51, title: "Jarang", score: 2 },
        { question_id: 51, title: "Sering", score: 3 },
        { question_id: 51, title: "Selalu", score: 4 },
        { question_id: 52, title: "Tidak Pernah", score: 1 },
        { question_id: 52, title: "Jarang", score: 2 },
        { question_id: 52, title: "Sering", score: 3 },
        { question_id: 52, title: "Selalu", score: 4 },
        { question_id: 53, title: "Tidak Pernah", score: 1 },
        { question_id: 53, title: "Jarang", score: 2 },
        { question_id: 53, title: "Sering", score: 3 },
        { question_id: 53, title: "Selalu", score: 4 },
        { question_id: 54, title: "Tidak Pernah", score: 1 },
        { question_id: 54, title: "Jarang", score: 2 },
        { question_id: 54, title: "Sering", score: 3 },
        { question_id: 54, title: "Selalu", score: 4 },
        { question_id: 55, title: "Ya", score: 1 },
        { question_id: 55, title: "Tidak", score: 0 },
        { question_id: 56, title: "Ya", score: 1 },
        { question_id: 56, title: "Tidak", score: 0 },
        { question_id: 57, title: "Ya", score: 1 },
        { question_id: 57, title: "Tidak", score: 0 },
        { question_id: 58, title: "Ya", score: 1 },
        { question_id: 58, title: "Tidak", score: 0 },
        { question_id: 59, title: "Ya", score: 1 },
        { question_id: 59, title: "Tidak", score: 0 },
        { question_id: 60, title: "Ya", score: 1 },
        { question_id: 60, title: "Tidak", score: 0 },
        { question_id: 61, title: "Ya", score: 1 },
        { question_id: 61, title: "Tidak", score: 0 },
        { question_id: 62, title: "Ya", score: 1 },
        { question_id: 62, title: "Tidak", score: 0 },
        { question_id: 63, title: "Ya", score: 1 },
        { question_id: 63, title: "Tidak", score: 0 },
        { question_id: 64, title: "Ya", score: 1 },
        { question_id: 64, title: "Tidak", score: 0 },
        { question_id: 65, title: "Ya", score: 1 },
        { question_id: 65, title: "Tidak", score: 0 },
        { question_id: 66, title: "Ya", score: 1 },
        { question_id: 66, title: "Tidak", score: 0 },
        { question_id: 67, title: "Ya", score: 1 },
        { question_id: 67, title: "Tidak", score: 0 },
        { question_id: 68, title: "Ya", score: 1 },
        { question_id: 68, title: "Tidak", score: 0 },
        { question_id: 69, title: "Ya", score: 1 },
        { question_id: 69, title: "Tidak", score: 0 },
        { question_id: 70, title: "Ya", score: 1 },
        { question_id: 70, title: "Tidak", score: 0 },
        { question_id: 71, title: "Ya", score: 1 },
        { question_id: 71, title: "Tidak", score: 0 },
        { question_id: 72, title: "Ya", score: 1 },
        { question_id: 72, title: "Tidak", score: 0 },
        { question_id: 73, title: "Ya", score: 1 },
        { question_id: 73, title: "Tidak", score: 0 },
        { question_id: 74, title: "Ya", score: 1 },
        { question_id: 74, title: "Tidak", score: 0 },
        { question_id: 75, title: "Ya", score: 1 },
        { question_id: 75, title: "Tidak", score: 0 },
        { question_id: 76, title: "Ya", score: 1 },
        { question_id: 76, title: "Tidak", score: 0 },
        { question_id: 77, title: "Ya", score: 1 },
        { question_id: 77, title: "Tidak", score: 0 },
        { question_id: 78, title: "Ya", score: 1 },
        { question_id: 78, title: "Tidak", score: 0 },
        { question_id: 79, title: "Ya", score: 1 },
        { question_id: 79, title: "Tidak", score: 0 },
        { question_id: 80, title: "Ya", score: 1 },
        { question_id: 80, title: "Tidak", score: 0 },
        { question_id: 81, title: "Ya", score: 1 },
        { question_id: 81, title: "Tidak", score: 0 },
        { question_id: 82, title: "Ya", score: 1 },
        { question_id: 82, title: "Tidak", score: 0 },
        { question_id: 83, title: "Ya", score: 1 },
        { question_id: 83, title: "Tidak", score: 0 },
        { question_id: 84, title: "Ya", score: 1 },
        { question_id: 84, title: "Tidak", score: 0 },
        { question_id: 85, title: "Ya", score: 1 },
        { question_id: 85, title: "Tidak", score: 0 },
        { question_id: 86, title: "Ya", score: 1 },
        { question_id: 86, title: "Tidak", score: 0 },
        { question_id: 87, title: "Ya", score: 1 },
        { question_id: 87, title: "Tidak", score: 0 },
        { question_id: 88, title: "Ya", score: 1 },
        { question_id: 88, title: "Tidak", score: 0 },
      ],
    });
  } catch (error) {
    console.log(error);
  }
};
